Add generate command
meniga/sonarscanner_dart pull request #1
Opened 2020-04-28 11:43 UTC by arturdm

2020-04-29 14:03 UTC, WezSieTato requested changes

2020-04-29 14:03 UTC, WezSieTato commented on test/command/generate_command_integration_test.dart
> +      expect(actualFile.readAsStringSync(), isNotEmpty);
Maybe we could equal this file to proper output file saved? Something like snapshot, but for text file.

2020-04-29 14:03 UTC, WezSieTato commented on lib/src/module_finder/module_finder.dart
> +class SonarModule extends Equatable {
`SonarModule` in separate file?

2020-04-29 14:03 UTC, WezSieTato commented on lib/src/command/sonarscanner_command.dart
> +abstract class SonarScannerCommand<T> extends Command<T> {
Just asking: are you think about more commands than generate?

2020-04-29 14:03 UTC, WezSieTato commented on lib/src/module_finder/module_finder.dart
> +class FindModuleResult extends Equatable {
What is the purpose of this class?

2020-04-29 14:29 UTC, arturdm commented on lib/src/command/sonarscanner_command.dart
> +abstract class SonarScannerCommand<T> extends Command<T> {
PR coming up - run command to download and run `sonar-scanner` https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

2020-04-29 14:30 UTC, arturdm commented on lib/src/module_finder/module_finder.dart
> +class FindModuleResult extends Equatable {
I didn't want to return `Future<Iterable<SonarModule>>` from `findModules` method but I guess I can refactor it.

2020-04-29 17:09 UTC, arturdm commented on test/command/generate_command_integration_test.dart
> +      expect(actualFile.readAsStringSync(), isNotEmpty);
The file contains absolute paths :(

2020-05-04 07:28 UTC, WezSieTato approved these changes

2020-05-04 08:31 UTC, merged